-- Story Comprehension Questions Export
-- Total questions: 32

INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(1, '1', 'What was the original Roman meaning of ''impedire'' based on its etymology?', '["To shackle the feet","To speed up movement","To create obstacles","To bind the hands"]'::jsonb, 'To shackle the feet', 'The text explicitly states that ''impedire'' meant ''to shackle the feet,'' built from ''in-'' (upon) and ''pes/pedis'' (foot).', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(1, '14', 'How did Christianity transform the meaning of ''impede'' in the 14th century?', '["It became purely physical obstruction","It became spiritual stumbling and sin","It became a tool for priests","It became a military strategy"]'::jsonb, 'It became spiritual stumbling and sin', 'The text explains that ''the soul now had feet'' and ''to sin was to stumble,'' showing how physical obstruction became spiritual metaphor.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(1, '16', 'What changed about ''impede'' during the Renaissance period?', '["It became more evil and dangerous","It shifted from bodies to minds and became inconvenient rather than evil","It became purely physical again","It was completely forgotten"]'::jsonb, 'It shifted from bodies to minds and became inconvenient rather than evil', 'The text states that ''motion itself became a metaphor'' and ''Impede...now followed minds instead of bodies. He was no longer evil, just inconvenient.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(1, '19', 'How did the industrial age transform ''impede''?', '["It became more moral and spiritual","It lost moral meaning and became mechanical inefficiency","It returned to its original physical meaning","It became a positive force for progress"]'::jsonb, 'It lost moral meaning and became mechanical inefficiency', 'The text states ''The moral heat was gone—only procedure remained'' and describes how it ''haunted the gears of systems,'' showing the shift from moral to mechanical.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(13, '1', 'What was the original Roman meaning of ''inhaerere''?', '["To be naturally part of something","To stick fast physically","To inherit property","To be morally right"]'::jsonb, 'To stick fast physically', 'The text explicitly states that ''inhaerere'' meant ''to stick fast'' and gives examples like ''wax to a seal'' and ''vine to its trellis'' - all physical adhesion.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(13, '14', 'How did medieval scholars transform the meaning of ''inherent''?', '["They made it purely physical","They made it metaphysical while keeping the idea of clinging","They made it about inheritance","They made it about morality only"]'::jsonb, 'They made it metaphysical while keeping the idea of clinging', 'The text states ''The physical became metaphysical—but the clinging remained'' and gives examples of ''Goodness clung to God; sin clung to the soul.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(13, '16', 'What changed about ''inherent'' during the Renaissance?', '["It became more religious","It became about divine will","It became about natural belonging rather than divine adherence","It became purely physical again"]'::jsonb, 'It became about natural belonging rather than divine adherence', 'The text states that qualities could be ''inherent'' ''without divine glue'' and ''by nature, not by God''s will,'' showing the shift from divine to natural.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(13, '19', 'How did modern science transform ''inherent''?', '["It made it more religious","It made it about divine order","It reduced it to structural properties without metaphysical meaning","It made it purely about morality"]'::jsonb, 'It reduced it to structural properties without metaphysical meaning', 'The text states ''No divine order, no metaphysical glue—just the way things were made'' and gives examples like ''magnetism in iron'' - purely structural properties.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(27, '1', 'What was the original Roman meaning of ''cohaerere''?', '["To be morally united","To stick together physically","To be intellectually consistent","To be emotionally connected"]'::jsonb, 'To stick together physically', 'The text explicitly states that ''cohaerere'' meant ''to stick together'' and gives physical examples like ''grains of sand in wet mortar'' and ''soldiers in formation.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(27, '14', 'How did medieval theologians use ''cohesive''?', '["To describe physical buildings","To describe military formations","To describe doctrinal unity held together by divine connection","To describe scientific principles"]'::jsonb, 'To describe doctrinal unity held together by divine connection', 'The text states that ''cohesive doctrine'' meant ''teachings that clung together like beads on a rosary—each truth connected to the next by divine thread.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(27, '16', 'What changed about ''cohesive'' during the Renaissance?', '["It became more religious","It became about divine connection","It became about rational rather than divine connection","It became purely physical"]'::jsonb, 'It became about rational rather than divine connection', 'The text states that ideas could be ''cohesive'' ''through logic alone—not divine thread, but rational connection'' and gives examples of ''coherent argument'' and ''cohesive theory.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(27, '19', 'How did modern science transform ''cohesive''?', '["It made it more religious","It made it about divine forces","It reduced it to physical forces and molecular bonds","It made it purely about logic"]'::jsonb, 'It reduced it to physical forces and molecular bonds', 'The text states that ''cohesive'' became ''a property of matter itself—the molecular forces that held atoms together'' and ''just the physics of attraction.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(42, '1', 'What was the original Roman meaning of ''spargere''?', '["To aim precisely","To scatter deliberately as strategy","To gather together","To destroy completely"]'::jsonb, 'To scatter deliberately as strategy', 'The text states that ''spargere'' meant ''to scatter'' and emphasizes it was ''the opposite of precision'' but ''strategy, not accident,'' with examples of hunters and generals using it tactically.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(42, '14', 'How did medieval warfare transform ''scattershot''?', '["It made it more precise","It made it about individual accuracy","It made it about volley tactics and coverage rather than precision","It made it purely defensive"]'::jsonb, 'It made it about volley tactics and coverage rather than precision', 'The text states that ''scattershot tactics'' meant ''arrows loosed in volleys—not aimed at one target, but spread across many'' and ''Scattering became covering; precision became coverage.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(42, '16', 'What changed about ''scattershot'' during the Renaissance?', '["It became more precise","It became about archery only","It became about artillery bombardment rather than archery volleys","It became purely defensive"]'::jsonb, 'It became about artillery bombardment rather than archery volleys', 'The text states that ''scattershot'' became ''what happened when you loaded a cannon with stones instead of a single ball'' and ''Scattering became artillery; coverage became bombardment.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(42, '19', 'How did modern warfare transform ''scattershot''?', '["It made it more strategic","It made it about precision and efficiency","It made it about random, wasteful, ineffective firing","It made it purely defensive"]'::jsonb, 'It made it about random, wasteful, ineffective firing', 'The text states that ''scattershot'' became ''what happened when you fired without aiming—random, wasteful, ineffective'' and ''What was once tactical became accidental.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(56, '1', 'What was the original Latin meaning of ''salire''?', '["To be important","To leap physically","To be hidden","To be slow"]'::jsonb, 'To leap physically', 'The text explicitly states that ''salire'' meant ''to leap'' and gives physical examples like ''deer springing from cover'' and ''water jumping from a fountain.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(56, '14', 'How did medieval scholars transform ''salient''?', '["They made it more physical","They made it about hidden meanings","They made it about ideas that jumped out and were obvious","They made it purely about movement"]'::jsonb, 'They made it about ideas that jumped out and were obvious', 'The text states that ''salient points'' meant ''ideas that jumped out from the text—not hidden meanings, but obvious ones that sprang to attention.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(56, '16', 'What changed about ''salient'' during the Renaissance?', '["It became more about hidden meanings","It became about surface prominence and immediate perception","It became purely physical","It became about slow, careful analysis"]'::jsonb, 'It became about surface prominence and immediate perception', 'The text states that ''salient features were what caught the eye first—not hidden depths, but surface prominence'' and gives examples of ''salient argument'' and ''salient detail.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(56, '19', 'How did modern psychology transform ''salient''?', '["It made it more about active leaping","It made it about contrast and passive standing out","It made it purely physical","It made it about hidden meanings"]'::jsonb, 'It made it about contrast and passive standing out', 'The text states that ''salient'' became ''what stood out from the background—not because it leaped, but because it contrasted'' and ''What was once active became passive; what was once leaping became standing.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(70, '1', 'What was the original Latin meaning of ''omittere''?', '["To include everything","To let go deliberately","To be careless","To be random"]'::jsonb, 'To let go deliberately', 'The text explicitly states that ''omittere'' meant ''to let go'' and emphasizes it was ''deliberate release, intentional abandonment'' with examples of scribes and generals making strategic choices.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(70, '14', 'How did medieval scribes transform ''omit''?', '["They made it about forgetting","They made it about careless mistakes","They made it about deliberate editing and choosing what to leave out","They made it purely about inclusion"]'::jsonb, 'They made it about deliberate editing and choosing what to leave out', 'The text states that ''omitting text'' meant ''leaving out what wasn''t essential—not forgetting, but choosing'' and ''Omitting became editing; release became refinement.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(70, '16', 'What changed about ''omit'' during the Renaissance?', '["It became more random","It became about purposeful selection and focus","It became purely about forgetting","It became about including everything"]'::jsonb, 'It became about purposeful selection and focus', 'The text states that ''omitting'' was ''what you did when you focused on the essential—not random exclusion, but purposeful selection'' and gives examples of scholars and writers making focused choices.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(70, '19', 'How did modern efficiency transform ''omit''?', '["It made it more deliberate","It made it about practical necessity and constraint rather than choice","It made it purely about forgetting","It made it about including everything"]'::jsonb, 'It made it about practical necessity and constraint rather than choice', 'The text states that ''omitting'' became ''what happened when you ran out of space or time—not deliberate selection, but practical necessity'' and ''What was once choice became constraint.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(83, '1', 'What was the original Latin meaning of ''perfungi''?', '["To perform carelessly","To perform completely and thoroughly","To perform partially","To perform randomly"]'::jsonb, 'To perform completely and thoroughly', 'The text explicitly states that ''perfungi'' meant ''to perform completely'' and emphasizes it was ''thorough execution, complete fulfillment'' with examples of priests and soldiers completing their duties fully.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(83, '14', 'How did medieval monks transform ''perfunctory''?', '["They made it about heartfelt devotion","They made it about ritual completion and obligation rather than emotion","They made it purely about performance","They made it about partial completion"]'::jsonb, 'They made it about ritual completion and obligation rather than emotion', 'The text states that ''perfunctory prayer'' meant ''prayer that fulfilled its purpose—not heartfelt devotion, but ritual completion'' and ''Performance became fulfillment; completion became obligation.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(83, '16', 'What changed about ''perfunctory'' during the Renaissance?', '["It became more inspired","It became about adequate execution rather than inspired effort","It became purely about emotion","It became about partial work"]'::jsonb, 'It became about adequate execution rather than inspired effort', 'The text states that ''perfunctory work'' was ''what got the job done—not inspired effort, but adequate execution'' and gives examples of clerks and functionaries meeting requirements.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(83, '19', 'How did modern industry transform ''perfunctory''?', '["It made it more thorough","It made it about minimal effort rather than adequate execution","It made it purely about inspired effort","It made it about complete fulfillment"]'::jsonb, 'It made it about minimal effort rather than adequate execution', 'The text states that ''perfunctory'' became ''what happened when you did just enough—not adequate execution, but minimal effort'' and ''What was once thorough became superficial.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(187, '1', 'What was the original Latin meaning of ''verisimilis''?', '["The truth itself","Like the truth or resembling truth","Completely false","Random appearance"]'::jsonb, 'Like the truth or resembling truth', 'The text explicitly states that ''verisimilis'' meant ''like the truth'' and emphasizes it was ''the appearance of truth, the semblance of reality'' with examples of actors and orators creating resemblance.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(187, '14', 'How did medieval theologians transform ''verisimilar''?', '["They made it about divine revelation","They made it about human reasoning that resembled divine wisdom","They made it purely about falsehood","They made it about random appearance"]'::jsonb, 'They made it about human reasoning that resembled divine wisdom', 'The text states that ''verisimilar doctrine'' meant ''teaching that looked like truth—not divine revelation, but human reasoning that resembled divine wisdom.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(187, '16', 'What changed about ''verisimilar'' during the Renaissance?', '["It became more abstract","It became about art that resembled life and reality","It became purely about divine wisdom","It became about random appearance"]'::jsonb, 'It became about art that resembled life and reality', 'The text states that ''verisimilar art'' was ''what looked like life—not life itself, but art that resembled reality'' and gives examples of paintings and stories creating lifelike appearance.', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;
INSERT INTO story_comprehension_questions (word_id, century, question, options, correct_answer, explanation, created_at, updated_at) VALUES
(187, '19', 'How did modern realism transform ''verisimilar''?', '["It made it more about appearance","It made it about accurate representation rather than mere appearance","It made it purely about semblance","It made it about random resemblance"]'::jsonb, 'It made it about accurate representation rather than mere appearance', 'The text states that ''verisimilar'' became ''what was true to life—not the appearance of truth, but the accuracy of representation'' and ''What was once semblance became accuracy.''', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)', 'Fri Oct 24 2025 19:01:43 GMT-0400 (Eastern Daylight Time)') ON CONFLICT (word_id, century) DO NOTHING;